### ISSUE TITLE
test_ext_peer sometimes fails

### ISSUE THREAD

**Issue by utamaro** [telehash/telehash-c#58]
https://travis-ci.org/utamaro/telehash-c/builds/65747029

https://github.com/utamaro/telehash-c
is exactly same as telehash/tehash-c.

test_ext_peer sometimes fails.
This fail seems to happen when  occuring a handshake again due to `src/link.c:258 link_receive_handshake() old/bad at:` error

**Comment by natevw** [comment]
Here's another log of just the test run, still trying to figure out at what point the actual communication happens within the codebase: https://gist.github.com/natevw/89efaabb727035618cc8

**Comment by natevw** [comment]
Sorry, lousy photo but I manually mapped out a decent part of the code calls that might be at play here:

![img_20150724_151117](https://cloud.githubusercontent.com/assets/265902/8885681/cbc72644-3216-11e5-9bf8-ff6003bf006c.jpg)

I noticed that the [first mesh_discover() call](https://gist.github.com/natevw/89efaabb727035618cc8#file-ext_peer-20log-L20-L21) does not get acknowledged (i.e. no event listeners/handlers) between the two nodes. Maybe it's not supposed to…still a lot of understanding to gain here…but it makes me wonder if the intermittent failure has something to do with the logic (IIRC) that determines which peer initiates the handshake. Maybe if the first mesh to get `link_pipe()`d [between the two](https://github.com/telehash/telehash-c/blob/ecd4e6c080876c33df5465d2667441637a780320/src/net/loopback.c#L27) happens to be of the right [order](https://github.com/telehash/telehash-c/blob/ecd4e6c080876c33df5465d2667441637a780320/src/e3x/exchange.c#L45) then it works, but otherwise fails?

**Comment by natevw** [comment]
Perhaps there is a bug in this logic: https://github.com/telehash/telehash-c/blob/ecd4e6c080876c33df5465d2667441637a780320/src/e3x/exchange.c#L119


Compare the results of some additional debugging on a [passing run](https://gist.github.com/natevw/97569f1c6e25cf2bbd96#file-pass_run-log-L28):

```
src/e3x/exchange.c:119 e3x_exchange_in() *debug* at=1437780607, x->in=0, x->order=2, x->out=1437780606
src/e3x/exchange.c:121 e3x_exchange_in() *debug* at=1437780607, x->in=1437780607, x->order=2, x->out=1437780606
```

Versus a [failing run](https://gist.github.com/natevw/97569f1c6e25cf2bbd96#file-fail_run-log-L28):

```
src/e3x/exchange.c:119 e3x_exchange_in() *debug* at=1437780642, x->in=0, x->order=1, x->out=1437780643
src/e3x/exchange.c:121 e3x_exchange_in() *debug* at=1437780642, x->in=0, x->order=1, x->out=1437780643
```

The two logs are placed (in my local build) right around the code in question. In the passing case, you can see that the `x->in` value gets updated to the incoming `at` number. In the failing case, it remains at `0`. 

**However**, I have seen "old/bad" complaints both when `x->order=1` *and* when `x->order=2` so perhaps it is not as simple as an even/odd vs. firstly/secondly-linked race.

I also note now that there are *two* links set up via `net_loopback_new` — so the reason that it failed about 55% of the time when I kept count is more murky. If the `net_loopback_new` had a 50% chance of failing each time, I would expect it to fail 75% of the times since both links need to be up for the test to pass…right?

**Comment by natevw** [comment]
Relevant reference is [Sequencing with `at`](https://github.com/telehash/telehash.org/blob/master/v3/e3x/handshake.md#sequencing-with-at) in the E3X exchange documentation.

Reading that, it's unclear to me why the value of `x->in` is checked so often against `x->out` in the code mentioned and the `link_receive_handshake` logic. All it seems is that:

* The incoming `at` should be higher than any previous *incoming* `at`, and match the sender's oddness/evenness
* If the incoming `at` is higher than the last outgoing `at`, an ack message should be sent. (It's unclear to me whether this ack should have the *incoming* `at` value, or increment by one to match the responder's parity.)

Might need to start debugging the message handling itself vs. the `at` tracking code next.

**Comment by dvanduzer** [comment]
As far as I can tell, the test was only failing because the test harness wasn't giving enough time for the link to finish establishing. Anecdotal evidence my patch works: https://travis-ci.org/dvanduzer/telehash-c/builds

**Comment by natevw** [comment]
Bizarre, I couldn't find any sort of concurrency/buffer/runloop opportunity in the loopback code, it basically works by recursion AFAICT (i.e. when one endpoint sends, the other syncronously processes, which may trigger a nested send, etc. — but all on the same callstack I thought).

Unless I'm missing a patch of threading code somewhere, I'm quite surprised adding a `sleep()` would change anything — assuming there's only one thread, what could possibly happen during a sleep in it to "finish" the link-making?

**Comment by natevw** [comment]
Update on earlier failure count statistics. I tweaked "test/Makefile" to only run `TESTS = ext_peer` and then used this script to count a whole bunch of runs:

```
num_runs=500
num_pass=0
for i in $(seq 1 $num_runs); do
  if make test; then
      num_pass=`expr $num_pass + 1`
  fi
done
```

I got "51 of 100" on the first try and then "233 of 500" after upping the `num_runs` and "246 of 500" running once more. So I retract any earlier guesses as to combining probabilities and whatnot, and will only go so far as to say "the test fails about half the time".

**Comment by natevw** [comment]
Other observations:

- I do see some "old/bad" handshake messages even when the overall testcase passes. So it could be something of a red herring.
- `grep thread -R src` in the repo yields no results. *HOWEVER* adding the `sleep` hack proposed in https://github.com/dvanduzer/telehash-c/commit/6b0860e7892aae8b0c2418fd8c874cac10397eee *does* change the percentage of passing results (!)


In fact, with the sleep hack added to the tests, all the lingering failures I see (e.g. 11 of 100 runs failed) are due to:

```
src/link.c:277 link_receive_handshake() link ready
src/ext/peer.c:109 peer_open_peer() connect delivered to ezn3jo2i6mhnt4ryc7fw3grcptyx44ctudr4yio5ke4pd2x6qlqa
src/ext/peer.c:109 peer_open_peer() connect delivered to a7v6aak2rvki3sfmjrh26ycpiivoz6yy57swtdhfh4tg75phjj6a
/bin/sh: line 1: 91151 Segmentation fault: 11  ./bin/test_$test
FAILED: ext_peer
```

Rather than the more typical:

```
rc/link.c:258 link_receive_handshake() old/bad at: {"at":1438889663 (1438889663,0,1438889664)
src/link.c:384 link_sync() link sync at 1438889664
src/ext/peer.c:109 peer_open_peer() connect delivered to 4rdktqd72o3j2nwa5sci5eazvagfgwgtc72pl6qi7eovovjcv6ua
src/ext/peer.c:109 peer_open_peer() connect delivered to j4gqxfquhp3lt4h7gu45b7oj6x2ecljspgbq6s7ut37oilnj57dq
----------------------------------------------
ext_peer.c:70: test FAILED:
Failed test: link_up(linkAC)
----------------------------------------------
FAILED: ext_peer
```

So now I'm really intrigued. Apparently there is some sort of asynchronous/concurrent behavior hiding somewhere in the codebase after all??

**Comment by natevw** [comment]
Oh! There's another explanation besides some hidden `pthread` calls I'm completely at a loss to find.

Despite @dvanduzer's (correct) insistence that the handshake "at" values aren't timestamps and shouldn't be treated or thought of as such etc. etc. — well, *in practice* in the current implementation they actually are based on the systems wall time. So it could be that that `sleep(1)` is "fixing" the test by skirting around an issue which the subsequent `peer_connect(linkAC, linkAB)` would otherwise have with its handshake processing.

Rephrased: the `sleep(1)` is *NOT* giving anything more time to process — there's no other thread/mechanism that could be _doing_ any processing *during* that sleep! Rather, the `sleep(1)` simply happens to bumps some handshake "at" values ahead into a less troublesome range. [That's my theory anyway.]

**Comment by natevw** [comment]
I've find/replaced some of the keynames to make it a bit clearer (still some pointer and timestamp differences between runs) but here's how the logs seems to consistently diverge between runs:

<img width="1530" alt="screen shot 2015-08-06 at 1 04 41 pm" src="https://cloud.githubusercontent.com/assets/265902/9122155/db7c3b54-3c3b-11e5-9ee2-a663b1a86f9a.png">

Note that in *both* the cases, there's an "old/bad" complaint. But in the passing case there's a lot more activity that happens before telehash internals return back to the test, that doesn't happen in the failing case. So I'm going to dive into the code again to see what conditionals might be at play after the point in the code where the `peer_open_peer` log happens.

**Comment by natevw** [comment]
Did some more code reading, log reviewing and general experimentation this afternoon:

1. adding a continuous `while (!link_up(…)) peer_connect(…)` loop in the tests did not result in any permanent hangs across a large number of test runs
2. after disabling the "old/bad" check in `link_receive_handshake`, the tests never failed in the way covered by this ticket (though the percentage failing due to #68 rose)

So despite all the waffling over whether the "old/bad handshake" warnings were even relevant, we now have two strong pieces of evidence implicating something about the handshake "at" values:

- the `sleep(1)` hack discussed above at https://github.com/telehash/telehash-c/issues/58#issuecomment-128490386
- the hack to disable the check entirely

Next step is to gain a better understanding of the exact handshake flow — particularly the even/odd ordering, which I still suspect is the case. Basically, figure out the differences in handshake flow in passing vs. failing, in order to clearly explain how the parity [or whatever ends up being the culprit] matters.

**Comment by dvanduzer** [comment]
In the *non*segfault situation, the test that fails is:

> fail_unless(link_up(linkAC));

However adding the call to sleep() right before that line doesn't fix the problem. For some reason, the sleep() call needs to be before the call to peer_connect() to be effective.

**Comment by dvanduzer** [comment]
@natevw Based on your screenshot, and based on my observations, it looks like successful cases involve *both* endpoints transmitting a "peer" request, which sounds extremely odd to me. I'll investigate further soon.

Your search/replace in the screenshot was very helpful, but instead of KEY_FIRST and KEY_SECOND you might find it instructive to do that as HASHNAME_A and HASHNAME_B next time. (These directly correspond to the identity hashnames of the meshA and meshB structures.)
